{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mydep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydep
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
{{- end }}
        
